services:
  web:
    image: odoo:19.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - POSTGRES_PASSWORD=odoo

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=odoo_db
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
      - ./init-db:/docker-entrypoint-initdb.d

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pg_admin
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: test@gmail.com
  #     PGADMIN_DEFAULT_PASSWORD: test
  #   ports:
  #     - "82:80"
  #   depends_on:
  #     - db

volumes:
  odoo-web-data:
  odoo-db-data:
